proxy:
  title: Cologne R User Group
  logo-url: https://secure.meetupstatic.com/photos/event/4/b/3/4/global_114619252.jpeg
  template-path: /templates/2col
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  container-wait-time: 60000
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: markus
    password: password
    groups: admins
  - name: theresa
    password: password
    groups: scientist
  usage-stats-url: http://myinfluxdb:8086/write?db=shinyproxy_usagestats
  docker:
      internal-networking: true
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: shinyproxy-net
  - id: 06_tabsets
    display-name: Another example
    description: Another application
    container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: shinyproxy-net
  - id: iris_clustering
    display-name: Iris K-Means Clustering
    description: Cluster your all time favorite dataset
    container-cmd: ["R", "-e", "shiny::runApp('root/app/')"]
    container-image: analytics/iris-clustering
    container-network: shinyproxy-net
  - id: dash_demo
    display-name: SVM Explorer
    description: Dash application written in python
    port: 8050
    container-cmd: ["python", "app.py"]
    container-image: analytics/svm
    container-network: shinyproxy-net
    access-groups: scientist

logging:
  file:
    shinyproxy.log
